version: '3'
services:
  # postgres:
  #   image: "postgres:latest"
  #   environment:
  #     POSTGRES_HOST_AUTH_METHOD: "trust"
  # redis:
  #   image: "redis:latest"
    
  # nginx:
  #   depends_on:
  #     - client
  #     - api
  #   restart: always
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - '3050:80'

  # api:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./server
  #   volumes:
  #     - /app/node_modules
  #     - ./server:/app
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_POST=6379
  #     - PGUSER=postgres
  #     - PGHOST=postgres
  #     - PGDATABASE=postgres
  #     - PGPASSWORD=postgres_password
  #     - PGPORT=5432
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    image: harishrathor/docker-k8s-client:latest
    environment:
      - WDS_SOCKET_PORT=0
    volumes:
      - /app/node_modules
      - ./client:/app
  # worker:
  #   build: 
  #     context: ./worker
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /app/node_modules
  #     - ./worker:/app


