apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ingress-nginx
  name: server-env-cm
data:
  REDIS_HOST: "redis-cluster-ip-service"
  REDIS_PORT: "6379"
  PGUSER: "postgres"
  PGHOST: "postgres-cluster-ip-service"
  PGDATABASE: "fibvalues"
  PGPORT: "5432"
