name: CI Checks and Build
env:
  NODE_VERSION: '18.13'
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
  REPO_NAME: docker-k8s-client
on: 
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - master
    - main
jobs:
  CodeQualityCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set node version to ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install modules
        run: npm --version && cd ./client/  && npm install
      - name: Run UTs
        run: cd ./client && npm run test
      - name: Set node version to ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
  Build: 
    runs-on: ubuntu-latest
    needs: CodeQualityCheck
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - 
        name: Build
        run: docker-compose -f docker-compose.yml build
      -
        name: Push
        run: docker push ${{env.DOCKER_USER}}/${{env.REPO_NAME}}:latest
        
      
        
        
