name: CI Checks and Build
env:
  NODE_VERSION: '18.13'
on: 
  push:
    branches:
      - "main"
  pull_request:
    branches:
    - main
jobs:
  CodeQualityCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set node version to ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install modules
        run: npm --version && cd ./client/  && npm install
      - name: Run UTs
        run: cd ./client && npm run test
      - name: Set node version to ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
  Build: 
    runs-on: ubuntu-latest
    needs: CodeQualityCheck
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        run: cd ./client && docker-compose build
      -
        name: Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest
      
        
        
